export const CONTACT_DETAIL_LOADING = 'CONTACT_DETAIL_LOADING';
export const CONTACT_DETAIL_SUCCESS = 'CONTACT_DETAIL_SUCCESS';
export const CONTACT_DETAIL_ERROR = 'CONTACT_DETAIL_ERROR';
export const CONTACT_REMOVE_ERROR = 'CONTACT_REMOVE_ERROR';
export const CONTACT_REMOVE_SUCCESS = 'CONTACT_REMOVE_SUCCESS';