export const CONTACT_FORM_LOADING = 'CONTACT_FORM_LOADING';
export const CONTACT_FORM_SUCCESS = 'CONTACT_FORM_SUCCESS';
export const CONTACT_FORM_ERROR = 'CONTACT_FORM_ERROR';
export const CONTACT_LOADING = 'CONTACT_LOADING';
export const CONTACT_REGISTER_COMPLETED = 'CONTACT_REGISTER_COMPLETED';
export const CONTACT_REGISTER_ERROR = 'CONTACT_REGISTER_ERROR';
export const CONTACT_REMOVE_COMPLETED = 'CONTACT_REMOVE_COMPLETED';
export const CONTACT_FORM_SUCCESS_WITH_CONTACT = 'CONTACT_FORM_SUCCESS_WITH_CONTACT';